import {isAuthenticated} from '../../auth';
import {database,readState} from '../../../db/store';
import {inMonth,shiftMonth,weekWindow,weekdays,shiftDay,type Project} from '../../../lib/planner';
export const dynamic='force-dynamic';
const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
const fail=(m:string):never=>{throw new Error(m)};
const text=(v:unknown,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:unknown,nullable=false)=>{if(nullable&&(v===null||v===undefined||v===''))return null;if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>10000000)fail('Enter a valid nonnegative number.');return v as number};
function validMonth(v:unknown){const s=text(v);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(s)||+s.slice(0,4)<2000||+s.slice(0,4)>2199)fail('Choose a valid month between 2000 and 2199.');return s}
function validDate(v:unknown){if(v===null||v===undefined||v==='')return null;const s=text(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s+'T00:00:00Z'))||new Date(s+'T00:00:00Z').toISOString().slice(0,10)!==s)fail('Choose a valid date.');return s}
export async function GET(){if(!await isAuthenticated())return reply({error:'Please sign in to open the planner.'},401);try{return reply(await readState())}catch(e){console.error('Read planner',e);return reply({error:'Could not load saved plans. Please try again.'},503)}}
export async function POST(req:Request){if(!await isAuthenticated())return reply({error:'Please sign in to save changes.'},401);if(req.headers.get('origin')&&new URL(req.headers.get('origin')!).host!==new URL(req.url).host)return reply({error:'Invalid request origin.'},403);try{const b=await req.json() as Record<string, any>,db=database(),id=text(b.id)||crypto.randomUUID();
 if(b.kind==='resource'){const name=text(b.name);if(!name)fail('Resource name is required.');const goal=num(b.goal)!;if(goal>1)fail('Utilization goal must be between 0% and 100%.');await db.prepare('INSERT INTO resources(id,name,role,location,weekly_hours,goal,active,eligible,notes) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,role=excluded.role,location=excluded.location,weekly_hours=excluded.weekly_hours,goal=excluded.goal,active=excluded.active,eligible=excluded.eligible,notes=excluded.notes').bind(id,name,text(b.role),text(b.location),num(b.weekly_hours),goal,b.active?1:0,b.eligible?1:0,text(b.notes,2000)).run()}
 else if(b.kind==='project'){const name=text(b.name);if(!name)fail('Project name is required.');const start=validDate(b.start_date),end=validDate(b.end_date);if((start&&!end)||(!start&&end)||(start&&end&&end<start))fail('Enter both dates, with end date on or after start date.');if(!b.id&&(!start||!end))fail('Start and end dates are required for a new project.');if(!['Active','Pipeline','On hold','Complete'].includes(b.status))fail('Choose a valid project status.');const prior=await db.prepare('SELECT month FROM allocations WHERE project_id=? AND hours>0').bind(id).all<{month:string}>();if(prior.results.some(a=>!inMonth({start_date:start,end_date:end} as Project,a.month)))fail('Existing hours fall outside these dates. Extend the dates or clear those monthly hours first.');const weekly=await db.prepare('SELECT week FROM weekly_allocations WHERE project_id=? AND hours>0').bind(id).all<{week:string}>();if(weekly.results.some(a=>{const w=weekWindow({start_date:start,end_date:end} as Project,a.week);return !weekdays(w.start,w.end)}))fail('A saved weekly plan falls outside these dates. Clear its hours or extend the dates.');await db.prepare('INSERT INTO projects(id,name,client,manager,start_date,end_date,budget,rate,billable,status,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,client=excluded.client,manager=excluded.manager,start_date=excluded.start_date,end_date=excluded.end_date,budget=excluded.budget,rate=excluded.rate,billable=excluded.billable,status=excluded.status,notes=excluded.notes').bind(id,name,text(b.client),text(b.manager),start,end,num(b.budget,true),num(b.rate,true),b.billable?1:0,b.status,text(b.notes,2000)).run();if(start&&end)await db.batch([db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(start.slice(0,7)),db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(end.slice(0,7))])}
 else if(b.kind==='month'){const month=validMonth(b.month);const statements=[db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(month)];if(b.copy){const prior=shiftMonth(month,-1),state=await readState(),rows=state.allocations.filter(a=>a.month===prior&&a.hours>0).map(a=>({...a,...state.projects.find(p=>p.id===a.project_id),active:state.resources.find(r=>r.id===a.resource_id)?.active}));for(const a of rows)if(a.active&&a.status!=='Complete'&&inMonth(a as Project,month))statements.push(db.prepare('INSERT INTO allocations(id,resource_id,project_id,month,hours,notes) VALUES (?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(crypto.randomUUID(),a.resource_id,a.project_id,month,a.hours,'Carried from '+prior+'. Confirm monthly hours.'))}await db.batch(statements)}
 else if(b.kind==='allocation'){const month=validMonth(b.month),resource=text(b.resource_id),project=text(b.project_id),hrs=num(b.hours)!;const [r,p]=await Promise.all([db.prepare('SELECT id FROM resources WHERE id=?').bind(resource).first(),db.prepare('SELECT * FROM projects WHERE id=?').bind(project).first<Project>()]);if(!r||!p)fail('Choose an existing resource and project.');if(hrs>0&&!inMonth(p!,month))fail('This month is outside the project dates. Edit the project dates first.');const state=await readState();if(state.allocations.some(a=>a.resource_id===resource&&a.project_id===project&&a.month===month&&a.weekly_managed))fail('This assignment is planned by week. Edit its hours in Weekly plan.');const prior=await db.prepare('SELECT actual,notes FROM allocations WHERE resource_id=? AND project_id=? AND month=?').bind(resource,project,month).first<{actual:number|null;notes:string}>(),actual=b.actual===undefined?(prior?.actual??null):num(b.actual,true),notes=b.notes===undefined?(prior?.notes??''):text(b.notes,2000);await db.batch([db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(month),db.prepare('INSERT INTO allocations(id,resource_id,project_id,month,hours,actual,notes) VALUES (?,?,?,?,?,?,?) ON CONFLICT(resource_id,project_id,month) DO UPDATE SET hours=excluded.hours,actual=excluded.actual,notes=excluded.notes').bind(id,resource,project,month,hrs,actual,notes)])}
 else if(b.kind==='capacity'){const month=validMonth(b.month),rid=text(b.resource_id);if(!await db.prepare('SELECT id FROM resources WHERE id=?').bind(rid).first())fail('Choose an existing resource.');await db.batch([db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(month),db.prepare('INSERT INTO capacity_adjustments(id,resource_id,month,leave_hours,capacity_override) VALUES (?,?,?,?,?) ON CONFLICT(resource_id,month) DO UPDATE SET leave_hours=excluded.leave_hours,capacity_override=excluded.capacity_override').bind(id,rid,month,num(b.leave_hours),num(b.capacity_override,true))])}
 else if(b.kind==='weekly'){const week=validDate(b.week);if(!week||new Date(week+'T00:00:00Z').getUTCDay()!==1)fail('Choose a Monday for the planning week.');validMonth(week!.slice(0,7));const resource=text(b.resource_id),project=text(b.project_id),hrs=num(b.hours)!;const [r,p]=await Promise.all([db.prepare('SELECT id FROM resources WHERE id=?').bind(resource).first(),db.prepare('SELECT * FROM projects WHERE id=?').bind(project).first<Project>()]);if(!r||!p)fail('Choose an existing resource and project.');const window=weekWindow(p!,week!);if(!weekdays(window.start,window.end))fail('This week has no working days inside the project dates.');const prior=await db.prepare('SELECT actual,notes FROM weekly_allocations WHERE resource_id=? AND project_id=? AND week=?').bind(resource,project,week).first<{actual:number|null;notes:string}>();await db.batch([db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(week!.slice(0,7)),db.prepare('INSERT INTO months(month) VALUES (?) ON CONFLICT DO NOTHING').bind(shiftDay(week!,6).slice(0,7)),db.prepare('INSERT INTO weekly_allocations(id,resource_id,project_id,week,hours,actual,notes) VALUES (?,?,?,?,?,?,?) ON CONFLICT(resource_id,project_id,week) DO UPDATE SET hours=excluded.hours,actual=excluded.actual,notes=excluded.notes').bind(id,resource,project,week,hrs,b.actual===undefined?(prior?.actual??null):num(b.actual,true),b.notes===undefined?(prior?.notes??''):text(b.notes,2000))])}
 else if(b.kind==='settings')await db.prepare('INSERT INTO settings(id,default_rate) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET default_rate=excluded.default_rate').bind('default',num(b.rate,true)).run();else fail('Unknown action.');return reply(await readState());
 }catch(e){console.error('Save planner',e);return reply({error:e instanceof Error?e.message:'Could not save changes. Please try again.'},422)}}

